# Generated by Django 6.0.3 on 2026-05-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('foto', models.ImageField(upload_to='animais/', verbose_name='Foto')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade')),
                ('tamanho', models.CharField(choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande')], max_length=10, verbose_name='Tamanho')),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=10, verbose_name='Sexo')),
                ('caracteristicas', models.TextField(verbose_name='Características')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('vacinado', models.BooleanField(default=False, verbose_name='Vacinado')),
                ('castrado', models.BooleanField(default=False, verbose_name='Castrado')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
    ]
