# Generated by Django 6.0.3 on 2026-05-11 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresseAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to='adocoes.animal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_interesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interesse de Adoção',
                'verbose_name_plural': 'Interesses de Adoção',
                'unique_together': {('animal', 'usuario')},
            },
        ),
    ]
