# Generated by Django 6.0.3 on 2026-05-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0002_interesseadocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='caracteristicas',
            field=models.TextField(help_text='Ex: Carinhoso, Brincalhão, Obediente', verbose_name='Características'),
        ),
    ]
