# Generated by Django 6.0.3 on 2026-05-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0003_alter_animal_caracteristicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Pássaro', 'Pássaro'), ('Outros', 'Outros')], default='Cachorro', max_length=20, verbose_name='Espécie'),
        ),
    ]
