# Generated by Django 6.0.3 on 2026-05-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0004_animal_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='idade_categoria',
            field=models.CharField(choices=[('Filhote', 'Filhote'), ('Jovem', 'Jovem'), ('Adulto', 'Adulto'), ('Sênior', 'Sênior')], default='Adulto', max_length=20, verbose_name='Categoria de Idade'),
        ),
    ]
